name: Python CI
on:
  pull_request:
    branches: [main, master]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ];
            then
              pip install -r requirements.txt
          fi

      - name: Run unit tests
        run: |
          if [ -d tests ];
            then
              pytest tests/
          else
            echo "no tests found on the repo"
          fi
